"""Subscription and Razorpay payment Pydantic schemas.

Contains models for creating subscription orders, verifying payment signatures,
and checking subscription status.
"""

from datetime import datetime
from typing import Literal
from pydantic import BaseModel, Field


class OrderCreate(BaseModel):
    """Schema for requesting a new payment order."""

    plan: Literal["pro", "family", "business"] = Field(
        ..., description="The billing plan to subscribe to (pro/family/business)"
    )


class OrderResponse(BaseModel):
    """Schema representing an order created via Razorpay."""

    razorpay_order_id: str = Field(..., description="The unique order ID generated by Razorpay")
    amount: int = Field(..., description="The amount to be paid in paise (e.g. 4900)")
    currency: str = Field("INR", description="Three-letter ISO currency code")
    key_id: str = Field(..., description="Razorpay public API key ID")


class PaymentVerify(BaseModel):
    """Schema for verifying a completed Razorpay payment signature."""

    razorpay_order_id: str = Field(..., description="Razorpay order ID")
    razorpay_payment_id: str = Field(..., description="Razorpay payment ID")
    razorpay_signature: str = Field(..., description="Hex signature generated by Razorpay")


class SubscriptionStatus(BaseModel):
    """Schema indicating the current status of a user's subscription."""

    plan: str = Field(..., description="The active plan (free/pro/family/business)")
    status: str = Field(..., description="Subscription status (active/expired/cancelled)")
    started_at: datetime = Field(..., description="Timestamp when the subscription started")
    expires_at: datetime = Field(..., description="Timestamp when the subscription expires")
